import React from 'react';
import { View } from 'react-native';
import { SvgXml } from 'react-native-svg';
import { MEDAL_BADGE_SVG } from '../../lib/medalBadges';

/**
 * Renders a single Honor medal badge from the designer art (lib/medalBadges.js,
 * generated by scripts/gen-medal-badges.mjs). Each badge bakes in its category
 * silhouette + colour; locked/unearned medals are dimmed. The on-screen name is
 * rendered separately by the caller (and is localised), so the art carries none.
 *
 * API is unchanged from the previous procedural version: { medal, size, earned }.
 */
export default function MedalIcon({ medal, size = 64, earned }) {
  const xml = medal ? MEDAL_BADGE_SVG[medal.key] : null;
  if (!xml) return null;
  const isEarned = earned ?? medal != null;
  return (
    <View style={{ opacity: isEarned ? 1 : 0.28 }}>
      <SvgXml xml={xml} width={size} height={size} />
    </View>
  );
}
