import React from 'react';
import { View } from 'react-native';
import { SvgXml } from 'react-native-svg';
import { MEDAL_BADGE_SVG } from '../../lib/medalBadges';

// A locked medal is struck from dead metal: the plate drops to Slate 2 and the
// engraving drops to Ink 2, so the badge keeps its silhouette and its detail but
// loses every tier colour. Dimming the coloured art with opacity was not enough
// — at 0/16 a wall of tinted badges still read as a set already won, and it
// contradicted both the counter and "No Honor Medals earned yet."
//
// Every generated badge is one bone plate (#f2eee6) plus accent marks in a
// single category colour (see lib/medalBadges.js), so the mapping is exact.
const PLATE_HEX = '#f2eee6';
const LOCKED_PLATE = '#8B8F98'; // Slate 2
const LOCKED_MARK = '#1A1D24'; // Ink 2

// Badge XML is static per key, so each locked variant is built once.
const lockedCache = new Map();

function lockedXml(key, xml) {
  const hit = lockedCache.get(key);
  if (hit) return hit;
  const out = xml.replace(
    /fill="(#[0-9a-fA-F]{3,8})"/g,
    (_match, hex) =>
      `fill="${hex.toLowerCase() === PLATE_HEX ? LOCKED_PLATE : LOCKED_MARK}"`,
  );
  lockedCache.set(key, out);
  return out;
}

/**
 * Renders a single Honor medal badge from the designer art (lib/medalBadges.js,
 * generated by scripts/gen-medal-badges.mjs). Earned badges carry the designer's
 * colour; locked ones are recoloured to a flat Slate 2 plate. The on-screen name
 * is rendered separately by the caller (and is localised), so the art carries none.
 *
 * API is unchanged from the previous procedural version: { medal, size, earned }.
 */
export default function MedalIcon({ medal, size = 64, earned }) {
  const xml = medal ? MEDAL_BADGE_SVG[medal.key] : null;
  if (!xml) return null;
  const isEarned = earned ?? medal != null;
  return (
    <View>
      <SvgXml
        xml={isEarned ? xml : lockedXml(medal.key, xml)}
        width={size}
        height={size}
      />
    </View>
  );
}
