import React from 'react';
import { View } from 'react-native';
import { SvgXml } from 'react-native-svg';
import { MEDAL_BADGE_SVG } from '../../lib/medalBadges';

// A locked medal is an empty setting, not a coin struck from dead metal.
//
// Two attempts got this wrong in opposite directions. Dimming the coloured art
// with opacity left a wall of tinted badges still reading as a set already won.
// Recolouring the plate to Slate 2 then overcorrected: sixteen mid-grey plates
// at full opacity became the brightest mass on the screen, so the things the
// player does NOT have outshouted the one action they should take.
//
// The rule that settles it: light fill belongs to earned medals only. A locked
// badge therefore goes DARKER than the card it sits on and carries its detail
// in the engraving — silhouette and structure preserved, no tier colour, and
// it recedes into the grid instead of competing with it.
//
// Every generated badge is one bone plate (#f2eee6) plus accent marks in a
// single category colour (see lib/medalBadges.js), so the mapping is exact.
const PLATE_HEX = '#f2eee6';
const LOCKED_PLATE = '#252932'; // Ink 3 — sits just above the card, reads as an empty slot
const LOCKED_MARK = '#5C6068'; // Slate — the engraving, legible against the dark plate

// Badge XML is static per key, so each locked variant is built once.
const lockedCache = new Map();

function lockedXml(key, xml) {
  const hit = lockedCache.get(key);
  if (hit) return hit;
  const out = xml.replace(
    /fill="(#[0-9a-fA-F]{3,8})"/g,
    (_match, hex) =>
      `fill="${hex.toLowerCase() === PLATE_HEX ? LOCKED_PLATE : LOCKED_MARK}"`,
  );
  lockedCache.set(key, out);
  return out;
}

/**
 * Renders a single Honor medal badge from the designer art (lib/medalBadges.js,
 * generated by scripts/gen-medal-badges.mjs). Earned badges carry the designer's
 * colour; locked ones are recoloured to a flat Slate 2 plate. The on-screen name
 * is rendered separately by the caller (and is localised), so the art carries none.
 *
 * API is unchanged from the previous procedural version: { medal, size, earned }.
 */
export default function MedalIcon({ medal, size = 64, earned }) {
  const xml = medal ? MEDAL_BADGE_SVG[medal.key] : null;
  if (!xml) return null;
  const isEarned = earned ?? medal != null;
  return (
    <View>
      <SvgXml
        xml={isEarned ? xml : lockedXml(medal.key, xml)}
        width={size}
        height={size}
      />
    </View>
  );
}
